name: Docker

on:
#   schedule:
#     - cron: '31 15 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_URL: github.com
  REGISTRY: docker.io
  DOCKERHUB_URL: https://hub.docker.com/r
  DOCKERHUB_ACCOUNT: hjwalt
  
permissions:
  contents: read
  packages: write

jobs:
  cx-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_ACCOUNT }}/cx-base
          tags: |
            type=raw,value=latest
          labels: |
            org.label-schema.name=cx-base
            org.label-schema.url=${{ env.DOCKERHUB_URL }}/${{ env.DOCKERHUB_ACCOUNT }}/cx-base
            org.label-schema.vcs-url=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.source=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.documentation=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}/blob/${{ env.GITHUB_REF }}/README.md

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./cx-base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
  cx-instances:
    needs: cx-base
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-builds: 
          - cx-docker-go
          - cx-docker-jdk-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.DOCKERHUB_ACCOUNT }}/${{ matrix.image-builds }}
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.label-schema.name=${{ matrix.image-builds }}
            org.label-schema.url=${{ env.DOCKERHUB_URL }}/${{ env.DOCKERHUB_ACCOUNT }}/${{ matrix.image-builds }}
            org.label-schema.vcs-url=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.source=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}
            org.opencontainers.image.documentation=${{ env.GITHUB_URL }}/${{ env.GITHUB_REPOSITORY }}/blob/${{ env.GITHUB_REF }}/README.md

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.image-builds }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
